// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjuEeo7ELp-PasACLyHHxG2dWPh_a3DsU',
    appId: '1:1057662772151:web:1e1298d3d7bcde1ec67e32',
    messagingSenderId: '1057662772151',
    projectId: 'e-learning-a9d40',
    authDomain: 'e-learning-a9d40.firebaseapp.com',
    storageBucket: 'e-learning-a9d40.firebasestorage.app',
    measurementId: 'G-6KQE99TTDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdPHGWrRVXVW5UI8As2yJiXmtXX6t1vxs',
    appId: '1:1057662772151:android:6d2ee53394a9e14ec67e32',
    messagingSenderId: '1057662772151',
    projectId: 'e-learning-a9d40',
    storageBucket: 'e-learning-a9d40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTCS7ZJi1S7Cr2W1SYWRhpmMjTH0ocMJs',
    appId: '1:1057662772151:ios:215e83ee4ff61204c67e32',
    messagingSenderId: '1057662772151',
    projectId: 'e-learning-a9d40',
    storageBucket: 'e-learning-a9d40.firebasestorage.app',
    iosBundleId: 'com.example.elearningDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTCS7ZJi1S7Cr2W1SYWRhpmMjTH0ocMJs',
    appId: '1:1057662772151:ios:215e83ee4ff61204c67e32',
    messagingSenderId: '1057662772151',
    projectId: 'e-learning-a9d40',
    storageBucket: 'e-learning-a9d40.firebasestorage.app',
    iosBundleId: 'com.example.elearningDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjuEeo7ELp-PasACLyHHxG2dWPh_a3DsU',
    appId: '1:1057662772151:web:a53d5524275c6be9c67e32',
    messagingSenderId: '1057662772151',
    projectId: 'e-learning-a9d40',
    authDomain: 'e-learning-a9d40.firebaseapp.com',
    storageBucket: 'e-learning-a9d40.firebasestorage.app',
    measurementId: 'G-1YGXGR9ERM',
  );
}
